import { useRef, useState, useCallback, useEffect } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { OrbitControls, Html } from '@react-three/drei'
import * as THREE from 'three'
import {
  aluMat, darkMat, steelMat, highlightMat,
  AM, DeployablePanel, usePart,
  BODY_X, BODY_Y, BODY_Z,
} from '../components/CubeSatModel'

// ── Component catalogue — sourced from IOLA-H1-RA-0001 v0.5 FRE ──────────────
// All CBE values from Section 13.3 mass budget and subsystem design (Section 10)
// [CBE] = Current Best Estimate pending vendor data per document notation
const COMPONENTS: Record<string, {
  name: string
  category: string
  status: string
  description: string
  specs: { label: string; value: string }[]
}> = {
  body: {
    name: 'Primary Structure',
    category: 'Structure',
    status: 'Design',
    description: 'The primary structure forms the foundation of the spacecraft, providing mechanical support, payload accommodation, and launch survivability. Its flat-satellite architecture maximizes available surface area for power generation, thermal management, communications, and future payload integration.',
    specs: [
      { label: 'Form Factor',      value: '12U XL Flat-Satellite' },
      { label: 'Stowed Dimensions',value: '226.3 × 226.3 × 366 mm' },
      { label: 'Internal Volume',  value: '~15–16 L usable' },
      { label: 'Material',         value: 'Aerospace-grade aluminium alloy' },
      { label: 'Structure Mass',   value: '2.6 kg' },
      { label: 'Architecture',     value: 'Flat deployed geometry' },
    ],
  },
  panelL: {
    name: 'Solar Wing — Port',
    category: 'Power',
    status: 'Design',
    description: 'Deployable solar wings provide primary onboard power generation. The system unfolds after deployment to significantly increase available surface area and energy production while maintaining a compact launch configuration.',
    specs: [
      { label: 'Power Output',     value: '~45 W per wing' },
      { label: 'Configuration',    value: 'Tri-fold deployable array' },
      { label: 'Panels Per Wing',  value: '3' },
      { label: 'Total Generation', value: '~102 W nominal' },
      { label: 'Orbit Avg Power',  value: '~40 W' },
      { label: 'Deployment',       value: 'Spring-loaded deployable hinges' },
    ],
  },
  panelR: {
    name: 'Solar Wing — Starboard',
    category: 'Power',
    status: 'Design',
    description: 'Deployable solar wings provide primary onboard power generation. The system unfolds after deployment to significantly increase available surface area and energy production while maintaining a compact launch configuration.',
    specs: [
      { label: 'Power Output',     value: '~45 W per wing' },
      { label: 'Deployed Span',    value: '~908 mm per wing' },
      { label: 'Total Generation', value: '~102 W nominal' },
      { label: 'Orbit Avg Power',  value: '~40 W' },
      { label: 'Deployment',       value: 'Spring-loaded deployable hinges' },
    ],
  },
  patch: {
    name: 'Communications System',
    category: 'Communications',
    status: 'Design',
    description: 'The communications system enables spacecraft command, telemetry, and payload data transmission. Critical spacecraft operations remain isolated from payload communications, improving operational reliability and mission safety.',
    specs: [
      { label: 'Command & Telemetry', value: 'S-Band / UHF' },
      { label: 'Payload Downlink',    value: 'X-Band' },
      { label: 'Peak Downlink Rate',  value: 'Up to 225 Mbps' },
      { label: 'Pass Energy',         value: '~3.3 Wh per 8-minute pass' },
      { label: 'Architecture',        value: 'Independent command and payload channels' },
    ],
  },
  dome: {
    name: 'Attitude Determination & Control',
    category: 'ADCS',
    status: 'Design',
    description: 'The ADCS maintains spacecraft orientation and pointing accuracy throughout the mission. It combines onboard sensors and control systems to support precise navigation, imaging operations, and autonomous spacecraft stabilization.',
    specs: [
      { label: 'Sensors',         value: 'Star Tracker, Sun Sensors, Magnetometer, Gyroscopes' },
      { label: 'Actuators',       value: 'Reaction Wheels, Magnetorquers' },
      { label: 'Navigation',      value: 'Integrated GNSS Receiver' },
      { label: 'Pointing Control',value: '≤0.1°' },
      { label: 'Pointing Knowledge', value: '≤0.03°' },
      { label: 'Modes',           value: 'Stabilized, Detumble, Safe Recovery' },
    ],
  },
  ant0: {
    name: 'Battery System',
    category: 'Power',
    status: 'Design',
    description: 'The onboard battery system stores energy generated by the solar arrays and supplies power during eclipse periods and peak operational loads. Integrated monitoring systems continuously manage battery health and performance.',
    specs: [
      { label: 'Chemistry',       value: 'Space-Rated Lithium-Ion' },
      { label: 'Capacity',        value: '150–200 Wh' },
      { label: 'Max Discharge',   value: '≤1.7C' },
      { label: 'Depth of Discharge', value: '≤5% per payload event' },
      { label: 'End-of-Life Reserve', value: '30% capacity margin' },
      { label: 'Battery Mass',    value: '1.5 kg' },
    ],
  },
  ant1: {
    name: 'Flight Computer',
    category: 'Avionics',
    status: 'Design',
    description: 'The flight computer serves as the central command and data management system for the spacecraft. It oversees mission operations, telemetry processing, onboard storage, and autonomous fault management.',
    specs: [
      { label: 'Architecture',    value: 'Dual-Processor System' },
      { label: 'Storage Capacity',value: '≥64 GB' },
      { label: 'Power Draw',      value: '~4 W continuous' },
      { label: 'Mass',            value: '0.8 kg' },
      { label: 'Fault Management',value: 'Autonomous Detection & Recovery' },
      { label: 'Functions',       value: 'Operations, Scheduling, Data Management' },
    ],
  },
  thr0: {
    name: 'Earth Observation Payload',
    category: 'Payload',
    status: 'Baseline',
    description: 'The baseline payload is a multispectral imaging system designed for Earth observation applications. The instrument supports environmental monitoring, agricultural analysis, and land-use assessment through multiple spectral bands.',
    specs: [
      { label: 'Spectral Bands',   value: 'Blue, Green, Red, Red Edge, Near Infrared' },
      { label: 'Applications',     value: 'Agriculture & Environmental Monitoring' },
      { label: 'Instrument Class', value: 'Commercial Imaging Payload' },
      { label: 'Pointing Control', value: '≤0.1°' },
      { label: 'Pointing Knowledge', value: '≤0.03°' },
      { label: 'Energy Per Scene', value: '~0.4 Wh per collection' },
    ],
  },
  thr1: {
    name: 'Demonstration Payload Bay',
    category: 'Payload',
    status: 'Configurable',
    description: 'The spacecraft includes a dedicated payload bay for future technology demonstrations and mission-specific experiments. This flexible architecture allows different payload configurations to be evaluated while preserving a common spacecraft platform.',
    specs: [
      { label: 'Payload Type',    value: 'Mission-Dependent' },
      { label: 'Architecture',    value: 'Modular Integration Bay' },
      { label: 'Mission Focus',   value: 'Technology Demonstration' },
      { label: 'Integration',     value: 'Standardized Payload Interface' },
      { label: 'Future Capability', value: 'Communications, Imaging, Research Payloads' },
      { label: 'Configuration',   value: 'Mission-Selectable' },
    ],
  },
  thr2: {
    name: 'Thermal Control System',
    category: 'Thermal',
    status: 'Design',
    description: 'The thermal control system maintains spacecraft temperatures within operational limits throughout the mission. Passive and active thermal management techniques work together to protect onboard electronics, payloads, and power systems.',
    specs: [
      { label: 'Thermal Protection', value: 'Multi-Layer Insulation' },
      { label: 'Active Control',     value: 'Heaters & Thermal Straps' },
      { label: 'Radiator Surface',   value: 'Dedicated Thermal Rejection Area' },
      { label: 'Nominal Bus Load',   value: '15–30 W' },
      { label: 'Imaging Load',       value: '30–50 W' },
      { label: 'Thermal Mass',       value: '0.7 kg' },
    ],
  },
  sep0: {
    name: 'Deployment Mechanisms',
    category: 'Structure',
    status: 'Design',
    description: 'Deployment systems control the release and positioning of movable spacecraft components after launch. These mechanisms enable the transition from launch configuration to operational configuration in orbit.',
    specs: [
      { label: 'Solar Wings',       value: 'Two Deployable Arrays' },
      { label: 'Wing Configuration',value: '3 Panels Per Wing' },
      { label: 'Deployment Span',   value: '~908 mm Per Wing' },
      { label: 'Mechanism Type',    value: 'Spring-Assisted Deployment' },
      { label: 'Structural Interface', value: 'Composite / Honeycomb Compatible' },
      { label: 'Function',          value: 'Controlled Orbital Deployment' },
    ],
  },
  sep1: {
    name: 'End-of-Life Disposal',
    category: 'Disposal',
    status: 'Compliant',
    description: 'The spacecraft is designed to naturally deorbit at the end of its operational life. This approach supports responsible orbital operations and long-term sustainability of the space environment.',
    specs: [
      { label: 'Disposal Method',   value: 'Passive Atmospheric Re-entry' },
      { label: 'Reference Orbit',   value: '500–550 km Sun-Synchronous Orbit' },
      { label: 'Spacecraft Mass',   value: '~22 kg' },
      { label: 'Estimated Decay',   value: '4–10 Years' },
      { label: 'Compliance',        value: 'Meets International Disposal Guidelines' },
      { label: 'End-of-Life',       value: 'Battery Passivation Procedure' },
    ],
  },
}

// ── Category colours ──────────────────────────────────────────────────────────
const CAT_COLOR: Record<string, string> = {
  Structure:      '#64748b',
  Power:          '#C8860A',
  Communications: '#1E5FA8',
  Avionics:       '#475569',
  ADCS:           '#0A2463',
  Payload:        '#7c3aed',
  Thermal:        '#dc2626',
  Disposal:       '#22c55e',
}

// Materials, AM, AG, PanelSegment, DeployablePanel, usePart — all from CubeSatModel

function getMatFor(id: string, selected: string | null, base: THREE.Material) {
  return id === selected ? highlightMat : base
}

// AM, AG, PanelSegment, DeployablePanel, usePart — imported from CubeSatModel

// ── Per-part callout offset: label sits here, line points back to part ────────
// [dx, dy] in screen-ish HTML space (pixels from part center)
const LABEL_OFFSETS: Record<string, [number, number, string]> = {
  // [x-offset px, y-offset px, anchor side for the pointer line]
  panelL:  [-110,   0,  'right' ],
  panelR:  [ 110,   0,  'left'  ],
  ant0:    [  60, -70,  'bottom'],
  ant1:    [ -60, -70,  'bottom'],
  patch:   [  90, -55,  'bottom'],
  dome:    [ -90, -55,  'bottom'],
  thr0:    [  90,  55,  'top'   ],
  thr1:    [ -90,  55,  'top'   ],
  thr2:    [   0,  80,  'top'   ],
  sep0:    [ 110,  30,  'left'  ],
  sep1:    [ 110, -30,  'left'  ],
}

// ── Callout label — offset pill with pointer line ─────────────────────────────
function PartLabel({ id, position, exploded, selected, onSelect }:
  { id: string; position: any; exploded: boolean; selected: string | null; onSelect: (id: string) => void }
) {
  const comp = COMPONENTS[id]
  const offset = LABEL_OFFSETS[id]
  if (!comp || !exploded || !offset) return null

  const [dx, dy, anchor] = offset
  const isSelected = id === selected
  const catColor = CAT_COLOR[comp.category] ?? '#1E5FA8'

  // Pointer line: from label edge back toward the part center
  // We draw it as an SVG absolutely positioned over the label container
  return (
    <AM position={position}>
      <Html
        center={false}
        style={{ pointerEvents: 'none', overflow: 'visible', userSelect: 'none' }}
        distanceFactor={2.2}
      >
        {/* Outer container — positioned so (0,0) is the part centre */}
        <div style={{ position: 'relative', width: 0, height: 0, overflow: 'visible' }}>

          {/* Pointer line — SVG drawn from origin to label offset */}
          <svg
            style={{
              position: 'absolute',
              overflow: 'visible',
              pointerEvents: 'none',
              left: 0, top: 0,
            }}
            width="1" height="1"
          >
            <line
              x1={0} y1={0}
              x2={dx} y2={dy}
              stroke={isSelected ? catColor : 'rgba(10,36,99,0.35)'}
              strokeWidth={isSelected ? '1.5' : '1'}
              strokeDasharray={isSelected ? 'none' : '4 3'}
            />
            {/* Dot at the part end */}
            <circle cx={0} cy={0} r="2.5" fill={isSelected ? catColor : 'rgba(10,36,99,0.4)'} />
          </svg>

          {/* Label pill — positioned at offset from part */}
          <div
            onClick={() => onSelect(id)}
            style={{
              position: 'absolute',
              left: dx, top: dy,
              transform: anchor === 'right'  ? 'translate(0, -50%)'  :
                         anchor === 'left'   ? 'translate(-100%, -50%)' :
                         anchor === 'bottom' ? 'translate(-50%, 0)' :
                                              'translate(-50%, -100%)',
              background: isSelected
                ? `linear-gradient(135deg, ${catColor}ee, ${catColor}cc)`
                : 'rgba(10,14,26,0.82)',
              color: isSelected ? '#fff' : '#f0f4ff',
              fontSize: '9.5px',
              fontWeight: 600,
              letterSpacing: '0.07em',
              textTransform: 'uppercase',
              padding: '4px 10px',
              borderRadius: '4px',
              border: `1px solid ${isSelected ? catColor : 'rgba(255,255,255,0.15)'}`,
              pointerEvents: 'all',
              cursor: 'pointer',
              backdropFilter: 'blur(8px)',
              whiteSpace: 'nowrap',
              transition: 'background 0.2s, border-color 0.2s',
              boxShadow: isSelected ? `0 2px 12px ${catColor}44` : '0 1px 4px rgba(0,0,0,0.3)',
            }}
          >
            {comp.name}
          </div>
        </div>
      </Html>
    </AM>
  )
}

// ── Satellite mesh ─────────────────────────────────────────────────────────────
function Satellite({
  exploded,
  deployed,
  selected,
  onSelect,
  rotating,
}: {
  exploded: boolean
  deployed: boolean
  selected: string | null
  onSelect: (id: string | null) => void
  rotating: boolean
}) {
  const group = useRef<THREE.Group>(null)
  const isDragging = useRef(false)

  useFrame((_, delta) => {
    if (!group.current || !rotating || isDragging.current) return
    group.current.rotation.y += delta * 0.14
  })

  // Horizon-1: 400×400×100mm "flying pizza box"
  const BX = BODY_X   // 0.400m
  const BY = BODY_Y   // 0.100m — thin pizza-box edge
  const BZ = BODY_Z   // 0.400m

  // Component positions matched to flat-sat geometry
  // X axis: wing direction, Y axis: face normal (thin), Z axis: depth (400mm)
  const posA0   = usePart('ant0',  [ BX*0.28,  BY/2+0.055,  BZ*0.25], exploded)
  const posA1   = usePart('ant1',  [-BX*0.28,  BY/2+0.055,  BZ*0.25], exploded)
  const posPatch= usePart('patch', [ BX*0.05, -BY/2-0.012,  BZ*0.08], exploded)
  const posDome = usePart('dome',  [-BX*0.18, -BY/2-0.012, -BZ*0.15], exploded)
  const posT0   = usePart('thr0',  [ BX*0.18,  BY/2+0.010,  BZ*0.10], exploded)
  const posT1   = usePart('thr1',  [-BX*0.18,  BY/2+0.010,  BZ*0.10], exploded)
  const posT2   = usePart('thr2',  [0,         0,            0      ], exploded)
  const posS0   = usePart('sep0',  [0,         0,           -BZ/3   ], exploded)
  const posS1   = usePart('sep1',  [0,         0,            BZ/3   ], exploded)

  const click = (id: string) => (e: any) => {
    e.stopPropagation()
    onSelect(selected === id ? null : id)
  }

  // MLI-covered materials for the flat-sat
  const mliMat = new THREE.MeshStandardMaterial({ color: '#c8860a', roughness: 0.08, metalness: 0.85 })
  const radiatorMat = new THREE.MeshStandardMaterial({ color: '#e8e8e8', roughness: 0.72, metalness: 0.0 })
  const solarBodyMat = new THREE.MeshStandardMaterial({ color: '#1a2a5e', roughness: 0.12, metalness: 0.0 })

  return (
    <group
      ref={group}
      rotation={[0.28, 0.55, 0.06]}
      onPointerDown={() => { isDragging.current = true }}
      onPointerUp={() => { setTimeout(() => { isDragging.current = false }, 80) }}
      onPointerMissed={() => onSelect(null)}
    >
      {/* Primary flat bus — 400×400×100mm MLI-wrapped body */}
      <mesh material={getMatFor('body', selected, mliMat)} castShadow receiveShadow onClick={click('body')}>
        <boxGeometry args={[BX, BY, BZ]} />
      </mesh>

      {/* Radiator face: -Z dedicated thermal face (white painted Al) */}
      <mesh position={[0, 0, -BZ/2 - 0.001]} material={radiatorMat}>
        <boxGeometry args={[BX - 0.004, BY - 0.004, 0.002]} />
      </mesh>

      {/* Nadir face: EO instrument window (dark optical) */}
      <mesh position={[0, -BY/2 - 0.001, BZ*0.1]} material={getMatFor('patch', selected, darkMat)} onClick={click('patch')}>
        <boxGeometry args={[0.080, 0.003, 0.090]} />
      </mesh>

      {/* Zenith face: body-mounted solar strips (~12W) */}
      <mesh position={[0, BY/2 + 0.001, 0]} material={solarBodyMat}>
        <boxGeometry args={[BX - 0.008, 0.002, BZ - 0.008]} />
      </mesh>

      {/* Corner rails: structural aluminium */}
      {([
        [ BX/2 - 0.009, 0,  BZ/2 - 0.009] as [number,number,number],
        [-BX/2 + 0.009, 0,  BZ/2 - 0.009] as [number,number,number],
        [ BX/2 - 0.009, 0, -BZ/2 + 0.009] as [number,number,number],
        [-BX/2 + 0.009, 0, -BZ/2 + 0.009] as [number,number,number],
      ]).map((pos, i) => (
        <mesh key={i} position={pos} material={aluMat}>
          <boxGeometry args={[0.012, BY + 0.002, 0.012]} />
        </mesh>
      ))}

      {/* Structural separation joints */}
      <AM position={posS0} material={getMatFor('sep0', selected, aluMat)} onClick={click('sep0')}>
        <boxGeometry args={[BX + 0.001, BY + 0.001, 0.003]} />
      </AM>
      <AM position={posS1} material={getMatFor('sep1', selected, aluMat)} onClick={click('sep1')}>
        <boxGeometry args={[BX + 0.001, BY + 0.001, 0.003]} />
      </AM>

      {/* Deployable solar wings from ±X long edges */}
      <DeployablePanel side={1}  deployed={deployed} exploded={exploded} selected={selected} onSelect={onSelect} />
      <DeployablePanel side={-1} deployed={deployed} exploded={exploded} selected={selected} onSelect={onSelect} />

      {/* TT&C whip antennas on zenith face */}
      <AM position={posA0} material={getMatFor('ant0', selected, steelMat)} onClick={click('ant0')}>
        <cylinderGeometry args={[0.0010, 0.0010, 0.110, 6]} />
      </AM>
      <AM position={posA1} material={getMatFor('ant1', selected, steelMat)} onClick={click('ant1')}>
        <cylinderGeometry args={[0.0010, 0.0010, 0.110, 6]} />
      </AM>

      {/* X-band downlink patch on +Z face */}
      <mesh position={[0, 0, BZ/2 + 0.003]} material={darkMat} onClick={click('ant1')}>
        <boxGeometry args={[0.055, BY * 0.7, 0.004]} />
      </mesh>

      {/* EO lens aperture (Payload A) */}
      <AM position={posDome} material={getMatFor('dome', selected, darkMat)} onClick={click('dome')}>
        <cylinderGeometry args={[0.018, 0.022, 0.024, 12]} />
      </AM>

      {/* ADCS reaction wheels — visible as discs */}
      <AM position={posT0} material={getMatFor('thr0', selected, steelMat)} onClick={click('thr0')}>
        <cylinderGeometry args={[0.028, 0.028, 0.012, 16]} />
      </AM>
      <AM position={posT1} material={getMatFor('thr1', selected, steelMat)} onClick={click('thr1')}>
        <cylinderGeometry args={[0.028, 0.028, 0.012, 16]} />
      </AM>

      {/* Battery pack (EPS) */}
      <AM position={posT2} material={getMatFor('thr2', selected, new THREE.MeshStandardMaterial({ color: '#2a3a5a', roughness: 0.4, metalness: 0.2 }))} onClick={click('thr2')}>
        <boxGeometry args={[BX * 0.55, BY * 0.60, BZ * 0.30]} />
      </AM>

      {/* 3D floating callout labels when exploded */}
      {(['ant0','ant1','patch','dome','thr0','thr1','thr2','sep0','sep1'] as const).map(id => {
        const posMap: Record<string, any> = {
          ant0: posA0, ant1: posA1,
          patch: posPatch, dome: posDome,
          thr0: posT0, thr1: posT1, thr2: posT2,
          sep0: posS0, sep1: posS1,
        }
        return (
          <PartLabel
            key={id}
            id={id}
            position={posMap[id]}
            exploded={exploded}
            selected={selected}
            onSelect={onSelect}
          />
        )
      })}
    </group>
  )
}

// ── Camera reset helper ───────────────────────────────────────────────────────
function CameraReset({ trigger }: { trigger: number }) {
  const { camera } = useThree()
  useEffect(() => {
    if (trigger === 0) return
    // Smoothly lerp back to default position
    const target = new THREE.Vector3(0.90, 0.70, 2.00)
    const start  = camera.position.clone()
    let t = 0
    const anim = () => {
      t += 0.04
      camera.position.lerpVectors(start, target, Math.min(t, 1))
      camera.lookAt(0, 0, 0)
      if (t < 1) requestAnimationFrame(anim)
    }
    requestAnimationFrame(anim)
  }, [trigger, camera])
  return null
}

// ── Detail panel ───────────────────────────────────────────────────────────────
function DetailPanel({ id, onClose }: { id: string; onClose: () => void }) {
  const comp = COMPONENTS[id]
  if (!comp) return null
  const catColor = CAT_COLOR[comp.category] ?? '#64748b'

  return (
    <div style={{
      position: 'fixed',
      top: '64px',
      bottom: '0',
      left: '0',
      width: '320px',
      background: 'rgba(255,255,255,0.97)',
      backdropFilter: 'blur(12px)',
      borderRight: '1px solid #e2e8f0',
      boxShadow: '4px 0 24px rgba(10,36,99,0.08)',
      display: 'flex',
      flexDirection: 'column',
      animation: 'panelIn 0.2s ease both',
      zIndex: 40,
    }}>
      {/* Header bar */}
      <div style={{ padding: '14px 16px 12px', borderBottom: '1px solid #e2e8f0' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
          <span style={{
            fontSize: '9px', fontWeight: 600, letterSpacing: '0.12em',
            textTransform: 'uppercase', color: catColor,
            background: `${catColor}15`,
            padding: '2px 8px', borderRadius: '100px',
          }}>
            {comp.category}
          </span>
          <button
            onClick={onClose}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              color: '#94a3b8', fontSize: '16px', lineHeight: 1,
              padding: '0 2px',
            }}
          >×</button>
        </div>
        <p style={{ fontSize: '15px', fontWeight: 600, color: '#111827', letterSpacing: '-0.01em', margin: 0 }}>
          {comp.name}
        </p>
        <p style={{ fontSize: '10px', color: catColor, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', marginTop: '3px' }}>
          {comp.status}
        </p>
      </div>

      {/* Scrollable body — description + specs */}
      <div style={{ flex: 1, overflowY: 'auto', minHeight: 0 }}>
        {/* Description */}
        <div style={{ padding: '14px 16px', borderBottom: '1px solid #f1f5f9' }}>
          <p style={{ fontSize: '12px', color: '#475569', lineHeight: '1.65', margin: 0 }}>
            {comp.description}
          </p>
        </div>

        {/* Specs table */}
        <div style={{ padding: '10px 16px 16px' }}>
          <p style={{ fontSize: '9px', fontWeight: 600, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#94a3b8', marginBottom: '8px', marginTop: 0 }}>
            Specifications
          </p>
          {comp.specs.map(s => (
            <div key={s.label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', padding: '5px 0', borderBottom: '1px solid #f8fafc', gap: '8px' }}>
              <span style={{ fontSize: '11px', color: '#94a3b8', fontWeight: 500, flexShrink: 0 }}>{s.label}</span>
              <span style={{ fontSize: '11px', color: '#111827', fontWeight: 600, textAlign: 'right' }}>{s.value}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// ── Toolbar ────────────────────────────────────────────────────────────────────
function Toolbar({
  exploded, onExplode, deployed, onToggleDeploy,
  onReset, selected, rotating, onToggleRotation,
}: {
  exploded: boolean
  onExplode: () => void
  deployed: boolean
  onToggleDeploy: () => void
  onReset: () => void
  selected: string | null
  rotating: boolean
  onToggleRotation: () => void
}) {
  return (
    <div style={{
      position: 'absolute', bottom: '28px', left: '50%',
      transform: 'translateX(-50%)',
      display: 'flex', alignItems: 'center', gap: '8px',
      background: 'rgba(255,255,255,0.95)',
      backdropFilter: 'blur(10px)',
      border: '1px solid #e2e8f0',
      borderRadius: '100px',
      padding: '6px 10px',
      boxShadow: '0 4px 16px rgba(10,36,99,0.10)',
      zIndex: 10,
    }}>
      <button onClick={onExplode} style={{
        background: exploded ? '#0A2463' : 'transparent',
        color: exploded ? '#fff' : '#0A2463',
        border: '1px solid',
        borderColor: exploded ? '#0A2463' : 'rgba(10,36,99,0.25)',
        borderRadius: '100px',
        padding: '5px 16px',
        fontSize: '11px', fontWeight: 600, letterSpacing: '0.06em',
        textTransform: 'uppercase', cursor: 'pointer',
        transition: 'all 0.2s',
      }}>
        {exploded ? 'Assemble' : 'Disassemble'}
      </button>

      <div style={{ width: '1px', height: '16px', background: '#e2e8f0' }} />

      {/* Deploy / Stow solar panels */}
      <button onClick={onToggleDeploy} style={{
        background: deployed ? 'rgba(200,134,10,0.1)' : 'transparent',
        color: deployed ? '#C8860A' : '#64748b',
        border: '1px solid',
        borderColor: deployed ? 'rgba(200,134,10,0.4)' : 'transparent',
        borderRadius: '100px',
        padding: '5px 14px',
        fontSize: '11px', fontWeight: 600, letterSpacing: '0.06em',
        textTransform: 'uppercase', cursor: 'pointer',
        transition: 'all 0.2s',
        display: 'flex', alignItems: 'center', gap: '5px',
      }}>
        {/* Solar panel icon */}
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round">
          <rect x="1" y="4" width="10" height="4" rx="0.5"/>
          <line x1="4" y1="4" x2="4" y2="8"/>
          <line x1="8" y1="4" x2="8" y2="8"/>
          <line x1="1" y1="6" x2="11" y2="6"/>
        </svg>
        {deployed ? 'Stow Arrays' : 'Deploy Arrays'}
      </button>

      <div style={{ width: '1px', height: '16px', background: '#e2e8f0' }} />

      {/* Rotation toggle */}
      <button onClick={onToggleRotation} style={{
        background: 'transparent',
        color: rotating ? '#64748b' : '#0A2463',
        border: 'none', borderRadius: '100px',
        padding: '5px 12px',
        fontSize: '11px', fontWeight: 500, cursor: 'pointer',
        letterSpacing: '0.04em', textTransform: 'uppercase',
        display: 'flex', alignItems: 'center', gap: '5px',
      }}>
        {/* Simple rotation icon */}
        <svg width="11" height="11" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
          <path d="M10 6A4 4 0 1 1 6 2"/>
          <path d="M10 2v4h-4"/>
        </svg>
        {rotating ? 'Stop' : 'Rotate'}
      </button>

      <div style={{ width: '1px', height: '16px', background: '#e2e8f0' }} />

      <button onClick={onReset} style={{
        background: 'transparent', color: '#64748b',
        border: 'none', borderRadius: '100px',
        padding: '5px 12px',
        fontSize: '11px', fontWeight: 500, cursor: 'pointer',
        letterSpacing: '0.04em', textTransform: 'uppercase',
      }}>
        Reset view
      </button>

      {selected && (
        <>
          <div style={{ width: '1px', height: '16px', background: '#e2e8f0' }} />
          <span style={{ fontSize: '11px', color: '#1E5FA8', fontWeight: 600, padding: '0 6px', letterSpacing: '0.04em' }}>
            ← {COMPONENTS[selected]?.name}
          </span>
        </>
      )}
    </div>
  )
}

// ── Hint ───────────────────────────────────────────────────────────────────────
function HintBar({ dismissed, onDismiss }: { dismissed: boolean; onDismiss: () => void }) {
  if (dismissed) return null
  return (
    <div
      onClick={onDismiss}
      style={{
        position: 'absolute', top: '20px', left: '50%',
        transform: 'translateX(-50%)',
        background: 'rgba(10,14,26,0.75)',
        backdropFilter: 'blur(8px)',
        color: 'rgba(255,255,255,0.7)',
        fontSize: '11px', fontWeight: 500,
        padding: '7px 18px', borderRadius: '100px',
        letterSpacing: '0.05em',
        cursor: 'pointer',
        zIndex: 10,
        whiteSpace: 'nowrap',
      }}>
      Drag to orbit · Click any part to inspect · Double-click to disassemble
    </div>
  )
}

// ── Page ───────────────────────────────────────────────────────────────────────
export default function Hardware() {
  const [exploded, setExploded]   = useState(false)
  const [deployed, setDeployed]   = useState(true)   // panels deployed by default
  const [selected, setSelected]   = useState<string | null>(null)
  const [resetTrigger, setReset]  = useState(0)
  const [hintDismissed, setHint]  = useState(false)
  const [rotating, setRotating]   = useState(true)

  const handleDoubleClick = useCallback(() => {
    setExploded(e => !e)
    setHint(true)
  }, [])

  const handleReset = useCallback(() => {
    setReset(n => n + 1)
    setSelected(null)
  }, [])

  return (
    <div style={{ position: 'relative', width: '100%', height: 'calc(100vh - 64px)', overflow: 'hidden', background: '#faf9f7' }}>

      {/* Page title — top left */}
      <div style={{
        position: 'absolute', top: '24px', left: '24px', zIndex: 10,
        pointerEvents: 'none',
      }}>
        <p style={{ fontSize: '10px', fontWeight: 600, letterSpacing: '0.16em', textTransform: 'uppercase', color: '#94a3b8', margin: 0 }}>
          Hardware · IOLA-H1-RA-0001 v0.5
        </p>
        <p style={{ fontSize: '18px', fontWeight: 600, letterSpacing: '-0.02em', color: '#111827', margin: '2px 0 0' }}>
          Horizon-1 · 12U XL Flat-Sat
        </p>
      </div>

      {/* Component count — top right */}
      <div style={{
        position: 'absolute', top: '24px', right: '24px', zIndex: 10,
        pointerEvents: 'none', textAlign: 'right',
      }}>
        <p style={{ fontSize: '10px', fontWeight: 600, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#94a3b8', margin: 0 }}>
          {Object.keys(COMPONENTS).length} components
        </p>
        <p style={{ fontSize: '11px', color: '#64748b', margin: '2px 0 0', letterSpacing: '0.02em' }}>
          Phase 0 / Phase A Architecture Study
        </p>
      </div>

      {/* 3D Canvas */}
      <Canvas
        shadows
        dpr={[1, 1.5]}
        camera={{ position: [0.90, 0.70, 2.00], fov: 50, near: 0.01, far: 30 }}
        onDoubleClick={handleDoubleClick}
        gl={{
          antialias: true,
          powerPreference: 'default',
          failIfMajorPerformanceCaveat: false,
          toneMapping: THREE.ACESFilmicToneMapping,
          toneMappingExposure: 1.12,
          outputColorSpace: THREE.SRGBColorSpace,
        }}
        style={{ background: '#faf9f7' }}
      >
        <OrbitControls
          enableZoom
          minDistance={0.4}
          maxDistance={3.5}
          enablePan={false}
          dampingFactor={0.08}
          enableDamping
        />

        <ambientLight intensity={0.60} />
        <directionalLight
          position={[-1.2, 1.8, -1.0]} intensity={2.6} color="#f9f0e4"
          castShadow
          shadow-mapSize={[1024, 1024]}
          shadow-camera-near={0.1} shadow-camera-far={10}
          shadow-camera-left={-1} shadow-camera-right={1}
          shadow-camera-top={1} shadow-camera-bottom={-1}
          shadow-radius={10} shadow-bias={-0.001}
        />
        <directionalLight position={[1.5, 0.5, -0.8]} intensity={0.8} color="#eef2ff" />
        <directionalLight position={[0.5, 1.0, 1.8]} intensity={1.0} color="#f0f4ff" />
        <pointLight position={[0.8, -0.5, 0.5]} intensity={0.3} color="#c8860a" />

        <Satellite exploded={exploded} deployed={deployed} selected={selected} onSelect={setSelected} rotating={rotating} />

        {/* Shadow catcher */}
        <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.28, 0]} receiveShadow>
          <planeGeometry args={[6, 6]} />
          <shadowMaterial transparent opacity={0.15} />
        </mesh>

        <CameraReset trigger={resetTrigger} />
      </Canvas>

      {/* Overlays */}
      <HintBar dismissed={hintDismissed} onDismiss={() => setHint(true)} />

      {selected && (
        <DetailPanel id={selected} onClose={() => setSelected(null)} />
      )}

      <Toolbar
        exploded={exploded}
        onExplode={() => setExploded(e => !e)}
        deployed={deployed}
        onToggleDeploy={() => setDeployed(d => !d)}
        onReset={handleReset}
        selected={selected}
        rotating={rotating}
        onToggleRotation={() => setRotating(r => !r)}
      />

      {/* Panel slide-in animation */}
      <style>{`
        @keyframes panelIn {
          from { opacity: 0; transform: translateX(-24px); }
          to   { opacity: 1; transform: translateX(0); }
        }
      `}</style>
    </div>
  )
}
